name: Run self InitialLoginTestIT

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Xvfb (for headless display)
        run: |
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: mvn -V -ntp install -DskipTests

      - name: Start Roller app 
        run: |
          mvn jetty:run > jetty.log 2>&1 &
          echo $! > jetty_pid.txt

      - name: Wait for Roller to be available
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:8080/roller/ | grep -q "Welcome to Roller!"; then
              echo "Roller is up!"
              break
            fi
            echo "Waiting for Roller..."
            sleep 500
          done
      
      - name: Run InitialLoginTestIT
        run: |
          cd it-selenium
          mvn -V -ntp -Dtest=org.apache.roller.selenium.InitialLoginTestIT test

      - name: Publish Test Report
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "it-selenium/target/surefire-reports/TEST-*.xml"
